---
# tasks file for software_basic_package
- name: include os dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: ensure basic software packages are installed
  package:
    pkg: "{{ basic_software_packages }}"
    state: present
  tags:
    - software
    - install
