---
# tasks file for software_basic_package
- name: include os dependent variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: enable epel repo
  block:
    - name: enable powertools
      ansible.builtin.import_role:
        name: robertdebock.powertools

    - name: Force all notified handlers to run at this point
      ansible.builtin.meta: flush_handlers

    - name: install epel repo
      ansible.builtin.package:
        pkg: epel-release
        state: present
  when:
    - "ansible_facts['os_family'] == 'RedHat'"
    - "not ansible_facts['distribution'] == 'Fedora'"

- name: ensure basic software packages are installed
  ansible.builtin.package:
    pkg: "{{ basic_software_packages }}"
    state: present
  tags:
    - software
    - install

- name: ensure basic software python packages are installed
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ basic_package_software_python_packages }}"
  tags:
    - software
    - install
