---
dependency:
  name: galaxy
  options:
    force: false
driver:
  name: docker
platforms:
  - name: basic-centos7
    image: "centos:7"
    pre_build_image: true
  - name: basic-almalinux8
    image: "almalinux:8"
    pre_build_image: true
  - name: basic-almalinux9
    image: "almalinux:9"
    pre_build_image: true
  - name: basic-debian11
    image: "debian:11"
    pre_build_image: true
  - name: basic-debian12
    image: "debian:12"
    pre_build_image: true
  - name: basic-debian-testing
    image: "debian:testing"
    pre_build_image: true
  - name: basic-fedora37
    image: "fedora:37"
    pre_build_image: true
  - name: basic-ubuntu2204
    image: "ubuntu:22.04"
    pre_build_image: true
role_name_check: 1
