---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: basic-centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    pre_build_image: true
  - name: basic-rockylinux8
    image: "geerlingguy/docker-rockylinux8-ansible"
    pre_build_image: true
  - name: basic-debian10
    image: "geerlingguy/docker-debian10-ansible:latest"
    pre_build_image: true
  - name: basic-debian11
    image: "geerlingguy/docker-debian11-ansible:latest"
    pre_build_image: true
  - name: basic-fedora35
    image: "fedora:35"
    pre_build_image: true
  - name: basic-ubuntu1604
    image: "geerlingguy/docker-ubuntu1604-ansible:latest"
    pre_build_image: true
  - name: basic-ubuntu1804
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    pre_build_image: true
  - name: basic-ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
