---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: basic-centos7
    image: "centos:7"
    pre_build_image: true
  - name: basic-rockylinux8
    image: "rockylinux:8"
    pre_build_image: true
  - name: basic-debian10
    image: "debian:10"
    pre_build_image: true
  - name: basic-debian11
    image: "debian:11"
    pre_build_image: true
  - name: basic-debian-testing
    image: "debian:testing"
    pre_build_image: true
  - name: basic-fedora36
    image: "fedora:36"
    pre_build_image: true
  - name: basic-ubuntu1604
    image: "ubuntu:16.04"
    pre_build_image: true
  - name: basic-ubuntu1804
    image: "ubuntu:18.04"
    pre_build_image: true
  - name: basic-ubuntu2004
    image: "ubuntu:20.04"
    pre_build_image: true
  - name: basic-ubuntu2204
    image: "ubuntu:22.04"
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
